[project]
name = "htmlcssjs2"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
python = ">=3.12.3,<3.13"
deno = ">=1.43.6,<1.44"
flask = ">=3.0.3,<3.1"
sqlalchemy = ">=2.0.30,<2.1"
flask-sqlalchemy = ">=3.0.3,<3.1"
